### ISSUE TITLE
Docker install only access from localhost - update instructions?

### ISSUE THREAD

**Issue by tokprof** [adRn-s/parkour2#78]
Hello! 

We are currently testing parkour if it could be useable for our lab. It looks verry nice. I had a problem getting it to work on one of our headless servers. I was however able to install it at home without a problem. Turns out the problem seemed to be that the docker installation only accepts traffic from the localhost. I was able to solve the problem by setting up a reverse proxy. Figuring out that was the limitation took me some time, the service seemed to only serve blank pages. Not until i did a 'curl -vv localhost:9980' and then a curl with -L to follow redirect could i figure out the limitation. It would have been helpful to have a note about this in the installation text.

**Comment by adRn-s** [comment]
You're right! We were hardly scratching the surface of the software requirements at the [Pre-requisites](https://github.com/maxplanck-ie/parkour2/wiki/Installation#pre-requisites) section at the instructions for Installation via Docker. I've added this paragraph now:

> In a server, you'll need to set passwords safely, configure the reverse proxy, configure TLS certificates in either Caddy or Nginx, add proper DNS records on your domain registrar, preserve data between docker runs, adjust the backup policy (e.g. with a remote/ off-site server), probably provision a mail server, etcetera. The following instructions are only meant to give you a glimpse into the ease of running our Web Application, ignoring all the system administration details. We highly recommend you get in contact to your IT department for a persistent installation. Nonetheless, the steps to get it up and running would be...

PS. Before, we had something similar but only at the bottom, after the instructions. It said... _"In a real scenario, you'll need to preserve data between docker runs, configure TLS certificates in the web server, add DNS records, adjust the backup policy (e.g. adding remote/ off-site), probably provision a mail server, etcetera."_
